#initialize run before stacking and primary generator actions
/run/initialize

/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/drawVolume

#/vis/geometry/set/visibility World 0 false
/vis/viewer/set/viewpointVector 1 0 0
/vis/scene/add/axes 0 0 0 0.5 m
/vis/scene/add/scale 20
/vis/scene/add/eventID
/vis/scene/add/magneticField 20 fullArrow

/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/scale 1 4 9

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add e+

